[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ai-data-summarizer"
version = "0.2.0"
description = "A local CLI tool that uses AI to summarize datasets."
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
authors = [
    { name = "Louie Bloomberg" }
]
dependencies = [
    "google-genai",
    "protobuf",
    "openai",
    "anthropic",
    "sentencepiece",
]

[dependency-groups]
dev = [
    "pytest",
]

[project.scripts]
ai-summarizer = "main:main"

[project.urls]
Homepage = "https://github.com/Bloomy52/ai-data-summarizer"

[tool.hatch.build.targets.wheel]
packages = ["."]
exclude = [
    "examples/",
    "*.md",
    ".venv/",
    "tests/",
    "summaries/",
    ".vscode/",
    ".gitignore",
    "requirements.txt",
    "pyproject.toml",
]